services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Hackathon
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - eece-network

  # Backend Service (Flask)
  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=Hackathon
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      - eece-network

  # Frontend Service (Highcharts Visualization)
  frontend:
    build: ./frontend
    container_name: flask-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CV_EXTRACTION_URL=http://cv-extraction-api:3001
      - JOB_DESCRIPTION_URL=http://job-description-api:3002
    networks:
      - eece-network

  # CV Extraction API
  cv-extraction-api:
    stdin_open: true
    tty: true
    build:
      context: ./CV-Format
      dockerfile: Dockerfile
    command: python cv_format.py
    ports:
      - "3001:3001"
    networks:
      - eece-network
    environment:
      - PORT=3001
      - OPENAI_API_KEY=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

  # Job Description API
  job-description-api:
    stdin_open: true
    tty: true
    build:
      context: ./job-description
      dockerfile: Dockerfile
    command: python job.py
    ports:
      - "3002:3002"
    networks:
      - eece-network
    environment:
      - PORT=3002
      - OPENAI_API_KEY=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

networks:
  eece-network:
    driver: bridge
